In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

file_path = r"C:\Users\DIVYA BASANTRAY\2020-Feb.csv"

In [2]:
df_sample = pd.read_csv(file_path, nrows=100000)

df_sample.shape

(100000, 9)

In [3]:
df_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   event_time     100000 non-null  object
 1   event_type     100000 non-null  object
 2   product_id     100000 non-null  int64
 3   category_id    100000 non-null  int64
 4   category_code  89180 non-null   object
 5   brand          81932 non-null   object
 6   price          100000 non-null  float64
 7   user_id        100000 non-null  int64
 8   user_session   100000 non-null  object
dtypes: float64(1), int64(3), object(5)
memory usage: 6.9+ MB

In [4]:
df_sample.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2020-02-01 00:00:00 UTC,view,100010426,2232732115290555244,apparel.shoes,NaN,19.31,581521975,82d5664d-7980-43e1-ab27-a2f05e991760
1,2020-02-01 00:00:00 UTC,view,100071077,2232732079706079299,sport.bicycle,crown,11.88,596313635,3df590c0-e667-4f5a-aa87-f47749cd6408
2,2020-02-01 00:00:00 UTC,view,1004665,2232732093077520756,construction.tools.light,samsung,838.23,608821035,3e271f43-db51-46bd-b215-c2907ed1a204
3,2020-02-01 00:00:01 UTC,view,1002544,2232732093077520756,construction.tools.light,apple,410.42,530488542,21f46782-fb36-4d5c-82d4-6dc26ae93fad
4,2020-02-01 00:00:01 UTC,view,100010151,2053013563835941749,appliances.kitchen.refrigerators,pulser,332.03,583795643,eddfe0e2-12f8-4357-b453-00786c9b0319

In [5]:
df_sample['event_type'].value_counts()

event_type
view        93001
cart         6011
purchase      988
Name: count, dtype: int64

In [6]:
df_sample.isnull().sum()

event_time           0
event_type           0
product_id           0
category_id          0
category_code    10820
brand            18068
price                0
user_id              0
user_session         0
dtype: int64

In [7]:
df_sample.duplicated().sum()

np.int64(942)

In [8]:
duplicates = df_sample[df_sample.duplicated(keep=False)]

duplicates.sort_values(
    ['user_id', 'event_time', 'product_id']
).head(20)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
17073,2020-02-01 01:08:47 UTC,cart,17300555,2232732098446229999,apparel.shoes.sandals,dior,88.55,512365496,56d3b01b-cdec-48ab-a86f-1c86e7be2794
17074,2020-02-01 01:08:47 UTC,cart,17300555,2232732098446229999,apparel.shoes.sandals,dior,88.55,512365496,56d3b01b-cdec-48ab-a86f-1c86e7be2794
17075,2020-02-01 01:08:47 UTC,cart,17300555,2232732098446229999,apparel.shoes.sandals,dior,88.55,512365496,56d3b01b-cdec-48ab-a86f-1c86e7be2794
17077,2020-02-01 01:08:47 UTC,cart,17300850,2232732098446229999,apparel.shoes.sandals,NaN,76.94,512365496,7f01a3c3-087f-448d-8805-83b2f90650d9
17078,2020-02-01 01:08:47 UTC,cart,17300850,2232732098446229999,apparel.shoes.sandals,NaN,76.94,512365496,7f01a3c3-087f-448d-8805-83b2f90650d9
17079,2020-02-01 01:08:47 UTC,cart,17300850,2232732098446229999,apparel.shoes.sandals,NaN,76.94,512365496,7f01a3c3-087f-448d-8805-83b2f90650d9
17081,2020-02-01 01:08:47 UTC,cart,17302509,2232732098446229999,apparel.shoes.sandals,chanel,180.18,512365496,8f759ed3-f109-4bfd-b7a6-bbc3f0b5b07f
17082,2020-02-01 01:08:47 UTC,cart,17302509,2232732098446229999,apparel.shoes.sandals,chanel,180.18,512365496,8f759ed3-f109-4bfd-b7a6-bbc3f0b5b07f
17083,2020-02-01 01:08:47 UTC,cart,17302509,2232732098446229999,apparel.shoes.sandals,chanel,180.18,512365496,8f759ed3-f109-4bfd-b7a6-bbc3f0b5b07f
97824,2020-02-01 03:15:20 UTC,cart,26400784,2053013553056579841,computers.peripherals.printer,NaN,365.26,512370755,4e5d9b2e-66d0-4e81-851b-5cbf2b700afb
97826,2020-02-01 03:15:20 UTC,cart,26400784,2053013553056579841,computers.peripherals.printer,NaN,365.26,512370755,4e5d9b2e-66d0-4e81-851b-5cbf2b700afb
20832,2020-02-01 01:19:52 UTC,cart,4502740,2232732102749585991,appliances.kitchen.hob,dauscher,180.16,512377994,9abcf751-aea8-4c60-abd4-fd4f9cb3b632
20834,2020-02-01 01:19:52 UTC,cart,4502740,2232732102749585991,appliances.kitchen.hob,dauscher,180.16,512377994,9abcf751-aea8-4c60-abd4-fd4f9cb3b632
26093,2020-02-01 01:34:01 UTC,cart,1003982,2053013555631882655,electronics.smartphone,huawei,115.50,512383048,9d5d8ea4-f25a-b9ec-7536-be34a2699a5c
26095,2020-02-01 01:34:01 UTC,cart,1003982,2053013555631882655,electronics.smartphone,huawei,115.50,512383048,9d5d8ea4-f25a-b9ec-7536-be34a2699a5c
80299,2020-02-01 02:57:23 UTC,cart,6301461,2053013554834964853,appliances.kitchen.kettle,willmark,40.93,512396385,a6cfdfbb-0df4-475b-ac55-872c1c7d6152
80300,2020-02-01 02:57:23 UTC,cart,6301461,2053013554834964853,appliances.kitchen.kettle,willmark,40.93,512396385,a6cfdfbb-0df4-475b-ac55-872c1c7d6152
80293,2020-02-01 02:57:23 UTC,cart,26402003,2053013553056579841,computers.peripherals.printer,sokolov,105.47,512396385,ea804d60-7f1a-4db4-897f-1049e42bf34b
80296,2020-02-01 02:57:23 UTC,cart,26402003,2053013553056579841,computers.peripherals.printer,sokolov,105.47,512396385,ea804d60-7f1a-4db4-897f-1049e42bf34b
75141,2020-02-01 02:50:58 UTC,view,7005237,2232732079009824823,kids.skates,NaN,97.55,512421492,e4b88374-b264-421b-b748-cbb699fe3e24

In [9]:
duplicate_count = df_sample.duplicated().sum()

print("Duplicate rows:", duplicate_count)
print("Duplicate percentage:", round(duplicate_count / len(df_sample) * 100, 2))
print("Rows after removing duplicates:", len(df_sample) - duplicate_count)

Duplicate rows: 942
Duplicate percentage: 0.94
Rows after removing duplicates: 99058

In [10]:
with open(file_path, 'r', encoding='utf-8') as f:
    total_rows = sum(1 for _ in f) - 1

print("Total rows:", total_rows)

Total rows: 55318565

In [13]:
event_counts = {}

for chunk in pd.read_csv(file_path, chunksize=500000):
    counts = chunk['event_type'].value_counts()

    for event, count in counts.items():
        event_counts[event] = event_counts.get(event, 0) + count

event_counts

{'view': 51232669, 'cart': 2885608, 'purchase': 1200288}

In [14]:
unique_users = set()
unique_sessions = set()

for chunk in pd.read_csv(
    file_path,
    usecols=['user_id', 'user_session'],
    chunksize=500000
):
    unique_users.update(chunk['user_id'].dropna().unique())
    unique_sessions.update(chunk['user_session'].dropna().unique())

print("Unique users:", len(unique_users))
print("Unique sessions:", len(unique_sessions))

Unique users: 4233206
Unique sessions: 13544595

In [16]:
del unique_users
del unique_sessions

In [17]:
cart_sessions = set()
purchase_sessions = set()

for chunk in pd.read_csv(
    file_path,
    usecols=['user_session', 'event_type'],
    chunksize=500000
):
    cart_sessions.update(
        chunk.loc[chunk['event_type'] == 'cart', 'user_session'].unique()
    )

    purchase_sessions.update(
        chunk.loc[chunk['event_type'] == 'purchase', 'user_session'].unique()
    )

print("Sessions with cart:", len(cart_sessions))
print("Sessions with purchase:", len(purchase_sessions))

Sessions with cart: 1660110
Sessions with purchase: 754013

In [18]:
cart_purchase_sessions = cart_sessions & purchase_sessions

print("Cart sessions:", len(cart_sessions))
print("Cart + purchase sessions:", len(cart_purchase_sessions))
print("Cart sessions without purchase:", len(cart_sessions - purchase_sessions))

Cart sessions: 1660110
Cart + purchase sessions: 700091
Cart sessions without purchase: 960019

In [19]:
view_sessions = set()

for chunk in pd.read_csv(
    file_path,
    usecols=['user_session', 'event_type'],
    chunksize=500000
):
    view_sessions.update(
        chunk.loc[chunk['event_type'] == 'view', 'user_session'].unique()
    )

print("Sessions with view:", len(view_sessions))

Sessions with view: 13217465

In [20]:
view_cart_sessions = view_sessions & cart_sessions

print("View sessions:", len(view_sessions))
print("View + cart sessions:", len(view_cart_sessions))
print("View sessions without cart:", len(view_sessions - cart_sessions))

View sessions: 13217465
View + cart sessions: 1383989
View sessions without cart: 11833476

In [21]:
view_cart_purchase_sessions = view_sessions & cart_sessions & purchase_sessions

print("View + cart + purchase sessions:", len(view_cart_purchase_sessions))

View + cart + purchase sessions: 698497

In [23]:
cart_file = r"C:\Users\DIVYA BASANTRAY\february_cart_events.csv"

first_chunk = True

for chunk in pd.read_csv(
    file_path,
    usecols=[
        'event_time',
        'event_type',
        'product_id',
        'category_id',
        'category_code',
        'brand',
        'price',
        'user_session'
    ],
    chunksize=500000
):
    
    cart_chunk = chunk[chunk['event_type'] == 'cart'].copy()

    if cart_chunk.empty:
        continue

    cart_chunk = cart_chunk.drop_duplicates()

    cart_chunk['purchased'] = cart_chunk['user_session'].isin(purchase_sessions)

    cart_chunk.to_csv(
        cart_file,
        mode='w' if first_chunk else 'a',
        index=False,
        header=first_chunk
    )

    first_chunk = False

print("Cart event file created.")

Cart event file created.

In [24]:
cart_df = pd.read_csv(cart_file)

In [25]:
cart_df.shape

(2656529, 9)

In [26]:
cart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2656529 entries, 0 to 2656528
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     object
 1   event_type     object
 2   product_id     int64
 3   category_id    int64
 4   category_code  object
 5   brand          object
 6   price          float64
 7   user_session   object
 8   purchased      bool
dtypes: bool(1), float64(1), int64(2), object(5)
memory usage: 164.7+ MB

In [27]:
cart_df['purchased'].value_counts()

purchased
False    1363052
True     1293477
Name: count, dtype: int64

In [28]:
duplicate_count = cart_df.duplicated().sum()

print("Exact duplicate rows remaining:", duplicate_count)
print("Original cart events:", 2885608)
print("Extracted cart records:", len(cart_df))
print("Records removed:", 2885608 - len(cart_df))

Exact duplicate rows remaining: 1
Original cart events: 2885608
Extracted cart records: 2656529
Records removed: 229079

In [29]:
cart_df = cart_df.drop_duplicates().copy()

print("Final cart records:", len(cart_df))
print("Exact duplicates remaining:", cart_df.duplicated().sum())

Final cart records: 2656528
Exact duplicates remaining: 0

In [30]:
cart_df['event_time'] = pd.to_datetime(cart_df['event_time'], utc=True)

cart_df['event_time'].dtype

datetime64[ns, UTC]

In [31]:
print("Start:", cart_df['event_time'].min())
print("End:", cart_df['event_time'].max())

Start: 2020-02-01 00:00:06+00:00
End: 2020-02-29 23:59:50+00:00

In [32]:
cart_df['date'] = cart_df['event_time'].dt.date
cart_df['hour'] = cart_df['event_time'].dt.hour
cart_df['day_of_week'] = cart_df['event_time'].dt.dayofweek
cart_df['day_name'] = cart_df['event_time'].dt.day_name()

cart_df[['event_time', 'date', 'hour', 'day_of_week', 'day_name']].head()

                 event_time        date  hour  day_of_week  day_name
0 2020-02-01 00:00:06+00:00  2020-02-01     0            5  Saturday
1 2020-02-01 00:00:07+00:00  2020-02-01     0            5  Saturday
2 2020-02-01 00:00:18+00:00  2020-02-01     0            5  Saturday
3 2020-02-01 00:00:18+00:00  2020-02-01     0            5  Saturday
4 2020-02-01 00:00:31+00:00  2020-02-01     0            5  Saturday

In [33]:
cart_session_summary = (
    cart_df[['user_session', 'purchased']]
    .drop_duplicates('user_session')
)

cart_session_summary['purchased'].value_counts()

purchased
False    960019
True     700091
Name: count, dtype: int64

In [34]:
cart_df['category_code'].isna().sum()

np.int64(203714)

In [35]:
category_cart = cart_df[
    ['user_session', 'category_code', 'purchased']
].copy()

category_cart['category_code'] = category_cart['category_code'].fillna('Unknown')

In [36]:
category_cart = category_cart.drop_duplicates(
    ['user_session', 'category_code']
)

In [37]:
category_summary = (
    category_cart
    .groupby('category_code')['purchased']
    .agg(
        cart_sessions='count',
        converted_sessions='sum'
    )
    .reset_index()
)

category_summary['abandoned_sessions'] = (
    category_summary['cart_sessions']
    - category_summary['converted_sessions']
)

category_summary['abandonment_rate'] = (
    category_summary['abandoned_sessions']
    / category_summary['cart_sessions']
    * 100
)

category_summary.sort_values(
    'cart_sessions',
    ascending=False
).head(15)

,category_code,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
87,construction.tools.light,657113,344041,313072,47.643556
0,Unknown,139227,43286,95941,68.909766
131,sport.bicycle,118267,45779,72488,61.291823
106,electronics.clocks,63778,24832,38946,61.064944
14,apparel.shoes,56099,20482,35617,63.489545
55,appliances.personal.massager,51696,23667,28029,54.218895
100,electronics.audio.headphone,37961,16573,21388,56.342035
32,appliances.environment.vacuum,31240,12925,18315,58.626761
50,appliances.kitchen.refrigerators,28848,10444,18404,63.796450
53,appliances.kitchen.washer,24138,10830,13308,55.132985
82,computers.peripherals.printer,23466,11497,11969,51.005710
19,apparel.shoes.sandals,22156,7845,14311,64.591984
115,furniture.bedroom.blanket,16664,7426,9238,55.436870
83,construction.components.faucet,16345,8895,7450,45.579688
20,apparel.shoes.slipons,15763,6620,9143,58.002918

In [38]:
category_summary_filtered = category_summary[
    category_summary['cart_sessions'] >= 1000
].sort_values(
    'abandonment_rate',
    ascending=False
)

category_summary_filtered.head(15)

,category_code,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
107,electronics.smartphone,4263,264,3999,93.807178
77,computers.notebook,3632,623,3009,82.846916
28,appliances.environment.air_conditioner,3960,733,3227,81.489899
88,construction.tools.painting,1486,294,1192,80.215343
120,furniture.living_room.chair,2914,642,2272,77.968428
12,apparel.scarf,12375,2793,9582,77.430303
46,appliances.kitchen.meat_grinder,1093,286,807,73.833486
27,apparel.underwear,5850,1561,4289,73.316239
123,furniture.universal.light,3470,936,2534,73.025937
109,electronics.telephone,1864,525,1339,71.834764
133,sport.ski,6099,1719,4380,71.815052
108,electronics.tablet,4097,1177,2920,71.271662
35,appliances.ironing_board,1287,371,916,71.173271
39,appliances.kitchen.dishwasher,1902,569,1333,70.084122
122,furniture.living_room.sofa,5544,1662,3882,70.021645

In [39]:
brand_cart = cart_df[
    ['user_session', 'brand', 'purchased']
].copy()

brand_cart['brand'] = brand_cart['brand'].fillna('Unknown')

brand_cart = brand_cart.drop_duplicates(
    ['user_session', 'brand']
)

brand_summary = (
    brand_cart
    .groupby('brand')['purchased']
    .agg(
        cart_sessions='count',
        converted_sessions='sum'
    )
    .reset_index()
)

brand_summary['abandoned_sessions'] = (
    brand_summary['cart_sessions']
    - brand_summary['converted_sessions']
)

brand_summary['abandonment_rate'] = (
    brand_summary['abandoned_sessions']
    / brand_summary['cart_sessions']
    * 100
)

brand_summary_filtered = brand_summary[
    brand_summary['cart_sessions'] >= 1000
].sort_values(
    'abandonment_rate',
    ascending=False
)

brand_summary_filtered.head(15)

,brand,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
2747,silverlit,1831,41,1790,97.760786
2175,nokian,2521,296,2225,88.258628
2549,rivertoys,1672,204,1468,87.799043
3328,yokohama,2780,457,2323,83.561151
3178,viatti,1665,284,1381,82.942943
1994,michelin,1167,205,962,82.433590
3048,toyo,1001,185,816,81.518482
1929,maxxis,1139,218,921,80.860404
3064,triangle,4071,816,3255,79.955785
2408,powertrac,1146,250,896,78.184991
2766,skad,2046,459,1587,77.565982
707,cordiant,6792,1548,5244,77.208481
3090,tunga,1446,337,1109,76.694329
940,electrolux,1018,240,778,76.424361
1736,lego,1079,259,820,75.996293

In [40]:
cart_df['price'].describe()

count    2.656528e+06
mean     2.915516e+02
std      3.300078e+02
min      0.000000e+00
25%      7.115000e+01
50%      1.724400e+02
75%      3.600900e+02
max      2.574070e+03
Name: price, dtype: float64

In [41]:
price_cart = cart_df[
    ['user_session', 'product_id', 'price', 'purchased']
].drop_duplicates(
    ['user_session', 'product_id']
)

price_cart['price_band'] = pd.cut(
    price_cart['price'],
    bins=[-1, 50, 100, 200, 350, 500, 1000, float('inf')],
    labels=[
        '$0–50',
        '$50–100',
        '$100–200',
        '$200–350',
        '$350–500',
        '$500–1,000',
        '$1,000+'
    ]
)

price_summary = (
    price_cart
    .groupby('price_band', observed=True)['purchased']
    .agg(
        cart_products='count',
        converted_products='sum'
    )
    .reset_index()
)

price_summary['abandoned_products'] = (
    price_summary['cart_products']
    - price_summary['converted_products']
)

price_summary['abandonment_rate'] = (
    price_summary['abandoned_products']
    / price_summary['cart_products']
    * 100
)

price_summary

,price_band,cart_products,converted_products,abandoned_products,abandonment_rate
0,$0–50,385121,132320,252801,65.641967
1,$50–100,222059,88768,133291,60.025038
2,$100–200,477608,235506,242102,50.690524
3,$200–350,328903,163499,165404,50.289599
4,$350–500,136406,63537,72869,53.420671
5,"$500–1,000",248869,119888,128981,51.826865
6,"$1,000+",94093,44139,49954,53.090028

In [42]:
session_time = (
    cart_df
    .sort_values('event_time')
    .drop_duplicates('user_session')
    [['user_session', 'event_time', 'purchased']]
    .copy()
)

session_time['hour'] = session_time['event_time'].dt.hour

hour_summary = (
    session_time
    .groupby('hour')['purchased']
    .agg(
        cart_sessions='count',
        converted_sessions='sum'
    )
    .reset_index()
)

hour_summary['abandoned_sessions'] = (
    hour_summary['cart_sessions']
    - hour_summary['converted_sessions']
)

hour_summary['abandonment_rate'] = (
    hour_summary['abandoned_sessions']
    / hour_summary['cart_sessions']
    * 100
)

hour_summary

,hour,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
0,0,8057,3007,5050,62.678416
1,1,14387,4838,9549,66.372420
2,2,29803,11139,18664,62.624568
3,3,57061,24084,32977,57.792538
4,4,82589,36137,46452,56.244778
5,5,98948,43359,55589,56.180014
6,6,109235,47954,61281,56.100151
7,7,113811,50059,63752,56.015675
8,8,116802,51541,65261,55.873187
9,9,115198,50742,64456,55.952360
10,10,112768,49369,63399,56.220736
11,11,105525,45308,60217,57.064203
12,12,98847,42571,56276,56.932431
13,13,92761,39019,53742,57.935986
14,14,91593,37237,54356,59.345146
15,15,90923,35321,55602,61.152844
16,16,83749,32343,51406,61.381031
17,17,75151,28773,46378,61.713084
18,18,62827,24893,37934,60.378500
19,19,42973,17673,25300,58.874177
20,20,25669,10828,14841,57.816822
21,21,15332,6644,8688,56.665797
22,22,9236,4234,5002,54.157644
23,23,6865,3018,3847,56.037873

In [43]:
session_products = (
    cart_df
    .groupby('user_session')
    .agg(
        unique_products=('product_id', 'nunique'),
        purchased=('purchased', 'first')
    )
    .reset_index()
)

session_products['product_count_band'] = pd.cut(
    session_products['unique_products'],
    bins=[0, 1, 2, 3, 5, 10, float('inf')],
    labels=[
        '1 product',
        '2 products',
        '3 products',
        '4–5 products',
        '6–10 products',
        '11+ products'
    ]
)

session_products['product_count_band'].value_counts().sort_index()

product_count_band
1 product        1484011
2 products        139468
3 products         25332
4–5 products        9305
6–10 products       1874
11+ products         119
Name: count, dtype: int64

In [44]:
session_summary = (
    session_products
    .groupby('product_count_band', observed=True)['purchased']
    .agg(
        cart_sessions='count',
        converted_sessions='sum'
    )
    .reset_index()
)

session_summary['abandoned_sessions'] = (
    session_summary['cart_sessions']
    - session_summary['converted_sessions']
)

session_summary['abandonment_rate'] = (
    session_summary['abandoned_sessions']
    / session_summary['cart_sessions']
    * 100
)

session_summary

,product_count_band,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
0,1 product,1484011,591298,892713,60.155417
1,2 products,139468,83927,55541,39.823472
2,3 products,25332,16996,8336,32.906995
3,4–5 products,9305,6516,2789,29.973133
4,6–10 products,1874,1276,598,31.910352
5,11+ products,119,78,41,34.453782

In [46]:
user_session_file = r"C:\Users\DIVYA BASANTRAY\february_user_sessions.csv"

first_chunk = True

for chunk in pd.read_csv(
    file_path,
    usecols=['user_id', 'user_session'],
    chunksize=500000
):
    
    chunk = chunk.drop_duplicates()

    chunk.to_csv(
        user_session_file,
        mode='w' if first_chunk else 'a',
        index=False,
        header=first_chunk
    )

    first_chunk = False

print("User-session file created.")

User-session file created.

In [47]:
user_session_df = pd.read_csv(user_session_file)

print("Rows:", len(user_session_df))
print("Unique users:", user_session_df['user_id'].nunique())
print("Unique sessions:", user_session_df['user_session'].nunique())
print("Duplicate user-session pairs:", user_session_df.duplicated().sum())

Rows: 13857231
Unique users: 4233206
Unique sessions: 13544595
Duplicate user-session pairs: 311666

In [48]:
user_session_df = user_session_df.drop_duplicates().copy()

print("Rows after deduplication:", len(user_session_df))
print("Duplicate pairs remaining:", user_session_df.duplicated().sum())

Rows after deduplication: 13545565
Duplicate pairs remaining: 0

In [49]:
cart_session_users = (
    user_session_df[
        user_session_df['user_session'].isin(
            cart_session_summary['user_session']
        )
    ]
    .drop_duplicates('user_session')
)

user_cart_sessions = (
    cart_session_users
    .groupby('user_id')['user_session']
    .nunique()
    .reset_index(name='cart_sessions')
)

user_cart_sessions['session_count_band'] = pd.cut(
    user_cart_sessions['cart_sessions'],
    bins=[0, 1, 2, 3, 5, float('inf')],
    labels=[
        '1 session',
        '2 sessions',
        '3 sessions',
        '4–5 sessions',
        '6+ sessions'
    ]
)

user_cart_sessions['session_count_band'].value_counts().sort_index()

session_count_band
1 session       470701
2 sessions      152650
3 sessions       69102
4–5 sessions     56167
6+ sessions      43161
Name: count, dtype: int64

In [51]:
user_session_outcomes = (
    cart_session_users
    .merge(
        user_cart_sessions[['user_id', 'session_count_band']],
        on='user_id',
        how='left'
    )
    .merge(
        cart_session_summary,
        on='user_session',
        how='inner'
    )
)

user_summary = (
    user_session_outcomes
    .groupby('session_count_band', observed=True)['purchased']
    .agg(
        cart_sessions='count',
        converted_sessions='sum'
    )
    .reset_index()
)

user_summary['abandoned_sessions'] = (
    user_summary['cart_sessions']
    - user_summary['converted_sessions']
)

user_summary['abandonment_rate'] = (
    user_summary['abandoned_sessions']
    / user_summary['cart_sessions']
    * 100
)

user_summary

,session_count_band,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
0,1 session,470701,162747,307954,65.424548
1,2 sessions,305300,119573,185727,60.834261
2,3 sessions,207307,82921,124386,60.000868
3,4–5 sessions,245038,101436,143602,58.603972
4,6+ sessions,431764,233414,198350,45.939448